keyframesSupport
ba-st/RenoirSt pull request #34
Opened 2019-11-25 15:37 UTC by HurrellT

Adding support for css keyframes for animations

2019-11-27 12:26 UTC, gcotelli requested changes
I saw some examples passing 'rotate(270deg)' as a string. If there's a list of such functions we can add support for them (we already have something similar for math functions). I would love to write it like `CssRotate by: 207 deg`

2019-11-27 12:26 UTC, gcotelli commented on source/RenoirSt/CssSelector.class.st
> +{ #category : #'as yet unclassified' }
This method is missing the category

2019-11-27 12:26 UTC, gcotelli commented on source/RenoirSt/CssSelector.class.st
> +{ #category : #'as yet unclassified' }
This method is missing the category

2019-11-27 12:26 UTC, gcotelli commented on source/RenoirSt/CssKeyframesRule.class.st
> +	^webkitCompatibility ifTrue: [ '@-webkit-keyframes' ] ifFalse: [ '@keyframes' ]
Do we really need this web-kit-compatibility flag? I'm in favor of always use the standard option (@keyframes) and to enable some kind of vendor mode if needed that adds the webkit  and mozilla rules. But I really hope that keyframes work on any modern browser. What do you think?

2019-11-27 12:31 UTC, gcotelli commented on source/RenoirSt/CssSelector.class.st
> +{ #category : #'as yet unclassified' }
It's also missing a test case

2019-11-27 12:31 UTC, gcotelli commented on source/RenoirSt/CssSelector.class.st
> +{ #category : #'as yet unclassified' }
It's also missing a test case

2019-11-27 12:43 UTC, gcotelli commented
Another thing I will change is that the keyframe selector must be one of: `from` `to` or a percentage. The current implementation provides the standard CssSelector builder so you can combine anything in invalid ways and write invalid CSS.

2019-11-29 18:48 UTC, HurrellT commented on source/RenoirSt/CssKeyframesRule.class.st
> +	^webkitCompatibility ifTrue: [ '@-webkit-keyframes' ] ifFalse: [ '@keyframes' ]
Flag removed in https://github.com/ba-st/RenoirSt/pull/34/commits/6fa379f18ffab27cacbc4db41f8c49b5baa55081

2019-11-29 18:49 UTC, HurrellT commented on source/RenoirSt/CssSelector.class.st
> +{ #category : #'as yet unclassified' }
Fixed in https://github.com/ba-st/RenoirSt/pull/34/commits/6fa379f18ffab27cacbc4db41f8c49b5baa55081

2019-11-29 18:49 UTC, HurrellT commented on source/RenoirSt/CssSelector.class.st
> +{ #category : #'as yet unclassified' }
Fixed in https://github.com/ba-st/RenoirSt/pull/34/commits/6fa379f18ffab27cacbc4db41f8c49b5baa55081

2019-11-29 20:04 UTC, gcotelli approved these changes

2019-12-02 12:25 UTC, merged